package config_test

import (
	"os"
	"path/filepath"
	"testing"

	"logauditorgo/internal/config"
)

func TestAutoGenerateDefaultConfig(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "config_test_*")
	if err != nil {
		t.Fatalf("create temp dir failed: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	origWd, _ := os.Getwd()
	defer os.Chdir(origWd)

	// 切换到临时空工作目录，模拟新环境首次运行
	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("chdir failed: %v", err)
	}

	cfg, err := config.Load("")
	if err != nil {
		t.Fatalf("Load config failed: %v", err)
	}

	if cfg.Server.Port != 8080 {
		t.Errorf("expected port 8080, got %d", cfg.Server.Port)
	}
	if cfg.Storage.DataDir != "LogAuditorGoData" {
		t.Errorf("expected DataDir LogAuditorGoData, got %s", cfg.Storage.DataDir)
	}

	// 验证在 LogAuditorGoData/ 下是否生成了 config.yaml
	expectedConfigFile := filepath.Join(tmpDir, "LogAuditorGoData", "config.yaml")
	if _, err := os.Stat(expectedConfigFile); os.IsNotExist(err) {
		t.Errorf("expected generated config file at %s, but not found", expectedConfigFile)
	}

	// 验证数据目录是否已创建
	expectedTasksDir := filepath.Join(tmpDir, "LogAuditorGoData", "tasks")
	if _, err := os.Stat(expectedTasksDir); os.IsNotExist(err) {
		t.Errorf("expected tasks dir at %s, but not found", expectedTasksDir)
	}
}
