package config_test

import (
	"os"
	"path/filepath"
	"testing"

	"logauditorgo/internal/config"
)

func TestAutoGenerateDefaultConfig(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "config_test_*")
	if err != nil {
		t.Fatalf("create temp dir failed: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	origWd, _ := os.Getwd()
	defer os.Chdir(origWd)

	// 切换到临时空工作目录，模拟新环境首次运行
	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("chdir failed: %v", err)
	}

	cfg, err := config.Load("")
	if err != nil {
		t.Fatalf("Load config failed: %v", err)
	}

	if cfg.Server.Port != 8080 {
		t.Errorf("expected port 8080, got %d", cfg.Server.Port)
	}
	if cfg.Storage.DataDir != "LogAuditorGoData" {
		t.Errorf("expected DataDir LogAuditorGoData, got %s", cfg.Storage.DataDir)
	}
	if cfg.Log.MaxSizeMB != 1024 {
		t.Errorf("expected Log.MaxSizeMB 1024, got %d", cfg.Log.MaxSizeMB)
	}
	if cfg.Log.MaxDays != 180 {
		t.Errorf("expected Log.MaxDays 180, got %d", cfg.Log.MaxDays)
	}
	if filepath.Clean(cfg.Log.Dir) != filepath.Clean(filepath.Join("LogAuditorGoData", "log")) {
		t.Errorf("expected Log.Dir LogAuditorGoData/log, got %s", cfg.Log.Dir)
	}

	// 验证在 LogAuditorGoData/ 下是否生成了 config.yaml
	expectedConfigFile := filepath.Join(tmpDir, "LogAuditorGoData", "config.yaml")
	if _, err := os.Stat(expectedConfigFile); os.IsNotExist(err) {
		t.Errorf("expected generated config file at %s, but not found", expectedConfigFile)
	}

	// 验证数据目录与日志目录是否已创建
	expectedLogDir := filepath.Join(tmpDir, "LogAuditorGoData", "log")
	if _, err := os.Stat(expectedLogDir); os.IsNotExist(err) {
		t.Errorf("expected log dir at %s, but not found", expectedLogDir)
	}
}

func TestUpdateAndSaveConfig(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "config_test_update_*")
	if err != nil {
		t.Fatalf("create temp dir failed: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	origWd, _ := os.Getwd()
	defer os.Chdir(origWd)
	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("chdir failed: %v", err)
	}

	configFile := filepath.Join(tmpDir, "test_config.yaml")
	_, err = config.Load(configFile)
	if err != nil {
		t.Fatalf("Load config failed: %v", err)
	}

	// 更新日志配置
	updated, err := config.UpdateLogConfig(2048, 90, "warn", "json")
	if err != nil {
		t.Fatalf("UpdateLogConfig failed: %v", err)
	}

	if updated.MaxSizeMB != 2048 || updated.MaxDays != 90 || updated.Level != "warn" || updated.Format != "json" {
		t.Fatalf("updated config values mismatch: %+v", updated)
	}

	// 重新 Load 验证持久化内容
	reloaded, err := config.Load(configFile)
	if err != nil {
		t.Fatalf("reload config failed: %v", err)
	}

	if reloaded.Log.MaxSizeMB != 2048 {
		t.Errorf("expected reloaded MaxSizeMB 2048, got %d", reloaded.Log.MaxSizeMB)
	}
	if reloaded.Log.MaxDays != 90 {
		t.Errorf("expected reloaded MaxDays 90, got %d", reloaded.Log.MaxDays)
	}
	if reloaded.Log.Level != "warn" {
		t.Errorf("expected reloaded Level 'warn', got %s", reloaded.Log.Level)
	}
}
